### ISSUE TITLE
Error when using ShapeletModel

### ISSUE THREAD

**Issue by sergey-sukhanov** [rtavenar/tslearn#13]
I am trying to fit ShapeletModel and passing an X array with data (dim=(72,78,6)) and Y array with labels (dim=(72,)) to the fit method. 

I am getting an shape error:

Traceback (most recent call last):
  File "/home/me/repos/core/ts/experiments/supervised_ts_clustering.py", line 50, in <module>
    instance.fit(x_train, y_train)
  File "/home/me/repos/core/ts/sota/supervised/shapelet.py", line 35, in fit
    self.instance.fit(TimeSeriesScalerMinMax().fit_transform(np.nan_to_num(data)), labels)
  File "/home/me/anaconda2/lib/python2.7/site-packages/tslearn/shapelets.py", line 288, in fit
    verbose=self.verbose_level)
  File "/home/me/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 1598, in fit
    validation_steps=validation_steps)
  File "/home/me/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 1183, in _fit_loop
    outs = f(ins_batch)
  File "/home/me/anaconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2273, in __call__
    **self.session_kwargs)
  File "/home/me/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/me/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/me/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/me/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
	 [[Node: shapelets_0_2/Reshape_1 = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](false_conv_0_2/convolution/Squeeze, shapelets_0_2/Reshape_1/shape)]]

Caused by op u'shapelets_0_2/Reshape_1', defined at:
  File "/home/me/repos/core/ts/experiments/supervised_ts_clustering.py", line 50, in <module>
    instance.fit(x_train, y_train)
  File "/home/me/repos/core/ts/sota/supervised/shapelet.py", line 35, in fit
    self.instance.fit(TimeSeriesScalerMinMax().fit_transform(np.nan_to_num(data)), labels)
  File "/home/me/anaconda2/lib/python2.7/site-packages/tslearn/shapelets.py", line 274, in fit
    self._set_model_layers(ts_sz=sz, d=d, n_classes=n_classes)
  File "/home/me/anaconda2/lib/python2.7/site-packages/tslearn/shapelets.py", line 375, in _set_model_layers
    for di in range(d)]
  File "/home/me/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 602, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/me/anaconda2/lib/python2.7/site-packages/tslearn/shapelets.py", line 85, in call
    xy = K.dot(x, K.transpose(self.kernel))
  File "/home/me/anaconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 991, in dot
    xt = tf.reshape(x, [-1, x_shape[-1]])
  File "/home/me/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2619, in reshape
    name=name)
  File "/home/me/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/me/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/me/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
	 [[Node: shapelets_0_2/Reshape_1 = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](false_conv_0_2/convolution/Squeeze, shapelets_0_2/Reshape_1/shape)]]

Process finished with exit code 1

Does anyone met the same error?

**Comment by rtavenar** [comment]
Hi,

Thanks for reporting this bug. I've never seen that before. Maybe this could be related to keras and/or tensorflow version. Could you tell me which version of these modules you have installed on your machine so that I can try to setup a similar virtualenv and check if I can reproduce the bug?

**Comment by sergey-sukhanov** [comment]
I have the following:
keras: 2.0.8
tensorflow: 1.3.0

**Comment by sergey-sukhanov** [comment]
I think we can remove this thread. I found the bug and this was on my side: I was passing to ts_sz not the number of segments but the dimensionality of the signal. Now, once i changed it, it doesn't throw me this error.

**Comment by rtavenar** [comment]
OK, great!
