### ISSUE TITLE
 installed tslearn via conda but gives errors when i import 

### ISSUE THREAD

**Issue by tapiwa7** [rtavenar/tslearn#63]
I am getting the follwing errors after installing tslearn via conda and running this line 
from tslearn.utils import to_time_series
The error is ModuleNotFoundError: No module named 'tslearn.utils'; 'tslearn' is not a package. What am i doing wrong?

**Comment by rtavenar** [comment]
Argh...

Wouldn't your working directory, or one of its subdirectories, or the current python file be called `tslearn`/`tslearn.py`?

**Comment by tapiwa7** [comment]
Oh yes my python file  was named tslearn.  Thank you for replying. Now i have the following error 
ImportError: bad magic number in 'tslearn': b'\x03\xf3\r\n'

    On Monday, 20 August 2018, 10:49:09 SAST, Romain Tavenard <notifications@github.com> wrote:  
 
 
Argh...

Wouldn't your working directory, or one of its subdirectories, or the current python file be called tslearn/tslearn.py?

**Comment by tapiwa7** [comment]
Everything is working now. Thank you 
    On Monday, 20 August 2018, 12:15:29 SAST, Tapiwa Charumbira <tapiwacharumbira@yahoo.com> wrote:  
 
  Oh yes my python file  was named tslearn.  Thank you for replying. Now i have the following error 
ImportError: bad magic number in 'tslearn': b'\x03\xf3\r\n'

    On Monday, 20 August 2018, 10:49:09 SAST, Romain Tavenard <notifications@github.com> wrote:  
 
 
Argh...

Wouldn't your working directory, or one of its subdirectories, or the current python file be called tslearn/tslearn.py?

**Comment by tapiwa7** [comment]
Thanx. It was my mistake. It worked well

**Comment by tapiwa7** [comment]
Hi 
I am getting  errors when i run the following 
X=pd.read_excel("E:/Machine Learning Projects/Data/Raw Files/Project 2/RawDatav3.xlsx")
X = X.fillna(0)
y =X['Leavers']
Z  = X.drop(['Leavers'], axis=1)
Z = to_time_series_dataset(Z)
y = to_time_series_dataset(y)
reg = TimeSeriesSVR(sz=64, d=2, kernel="gak", gamma="auto")
predict = reg.fit(Z, y).predict(Z)

Traceback (most recent call last):  File "C:\Users\t\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\indexes\base.py", line 2393, in get_loc    return self._engine.get_loc(key)  File "pandas\_libs\index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5239)  File "pandas\_libs\index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc (pandas\_libs\index.c:5085)  File "pandas\_libs\hashtable_class_helper.pxi", line 1207, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20405)  File "pandas\_libs\hashtable_class_helper.pxi", line 1215, in pandas._libs.hashtable.PyObjectHashTable.get_item (pandas\_libs\hashtable.c:20359)KeyError: 0
During handling of the above exception, another exception occurred:

What am i doing wrong?
